# The Docker image that will be used to build your app
image: node:lts
# Functions that should be executed before the build script is run
before_script:
  - export NODE_OPTIONS=--max_old_space_size=4096
  - npm install -g pnpm
  - pnpm install
pages:
  script:
    - pnpm docs:build
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - src/.vuepress/.dist
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
