version: '1.0'
name: pipeline-20230108
displayName: 自动构建
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-cf517f43
    displayName: 构建网页
    strategy: fast
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 安装工具'
          - npm install -g pnpm
          - pnpm install
          - ''
          - '# 构建'
          - pnpm docs:build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./src/.vuepress/dist
        caches:
          - ~/src/.vuepress/.cache
          - ~/src/.vuepress/.temp
        notify:
          - certificate: 77d5a450-216c-013b-e2e0-62a419196a2a
            events:
              - fail
              - cancel
              - skip
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: weixin
        strategy:
          retry: '0'
  - name: stage-2ca9db50
    displayName: 部署
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        notify:
          - certificate: 77d5a450-216c-013b-e2e0-62a419196a2a
            events:
              - fail
              - cancel
              - skip
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: weixin
        strategy:
          retry: '0'
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID:
          ID: hestudio
          hostID:
            - c5403908-f2b9-4c20-927a-bcdb34690878
        deployArtifact:
          - source: build
            name: output
            target: ~/gitee_go/deploy
            dependArtifact: BUILD_ARTIFACT
        script:
          - tar zxvf ~/gitee_go/deploy/output.tar.gz -C /data/wwwroot/
          - cd /data/wwwroot/
          - python3 add.py
          - cp ads.txt dist/
          - rm -rf www.hestudio.xyz/*
          - cp -r dist/* www.hestudio.xyz/
          - cp -r .well-known www.hestudio.xyz/
          - echo "All is Successfully!"
        notify:
          - certificate: 77d5a450-216c-013b-e2e0-62a419196a2a
            events:
              - fail
              - cancel
              - skip
              - success
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: weixin
        strategy:
          retry: '0'
          expression: []
strategy:
  blocking: true