name: Deploy Blog
on:
  push:
    branches:
      - master

# 任务
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # 步骤 根据步骤执行任务
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      - name: Installation dependency
        run: pnpm install
      - name: Build Website
        run: pnpm docs:build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: src/.vuepress/dist


  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - name: Clean up old files on the website
        run: sudo rm -rf /www/wwwroot/www/*
      - name: Import website files
        run: sudo cp -r * /www/wwwroot/www/
      - name: Refresh CDN
        run: node ~/refresh/www.js
