name: Deploy Blog
on:
  push:
    branches:
      - master

# 任务
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # 步骤 根据步骤执行任务
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm docs:build
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: src/.vuepress/dist


  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - run: sudo rm -rf /www/wwwroot/www/*
      - run: sudo cp -r * /www/wwwroot/www/