name: Deploy Blog
on:
  push:
    branches:
      - master

env:
  TZ: Asia/Shanghai

# 任务
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # 步骤 根据步骤执行任务
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: .
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 9
      - name: Installation dependency
        run: pnpm install
      - name: Build Website
        run: pnpm docs:build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: src/.vuepress/dist

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: Clean up old files on the website
        run: sudo rm -rf /www/wwwroot/www/*
      - name: Import website files
        run: sudo cp -r * /www/wwwroot/www/
